// Template for whenever I refresh the main branch. and to re-add the submodules afterwards.

name: Add Tweaks

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add uYouPlus submodules
        run: |
          git submodule add https://github.com/PoomSmart/YTVideoOverlay.git Tweaks/YTVideoOverlay
          git submodule add https://github.com/PoomSmart/YTClassicVideoQuality.git Tweaks/YTClassicVideoQuality
          git submodule add https://github.com/PoomSmart/YouQuality.git Tweaks/YouQuality
          git add .
          git commit -m "added uYouPlusExtra submodules"
          git push origin

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
