name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "updated submodules"
          git push origin
